apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /koina
  annotations:
    internal.kpt.dev/upstream-identifier: apps/v1|Deployment|koina|koina
  name: koina
  namespace: koina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koina
  template:
    metadata:
      labels:
        app: koina
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      containers:
        - name: koina
          image: us-east4-docker.pkg.dev/koina-504021/koina/koina:pdi-test
          env:
            - name: MODEL_PATTERN
              value: "Prosit,Deeplc,IM2Deep"
          ports:
            - name: grpc
              containerPort: 8500
              protocol: TCP
            - name: http
              containerPort: 8501
              protocol: TCP
            - name: metrics
              containerPort: 8502
              protocol: TCP
          resources:
            requests:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          startupProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            periodSeconds: 30
            failureThreshold: 80
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            periodSeconds: 30
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
